# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nyptelegram
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-python-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-python-rest-api

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  role: arn:aws:iam::017820698732:role/MyLambdaDynamoDBExecutionRole

  environment:
    STAGE: ${self:provider.stage}
    MY_ENV_VAR: 'my-value'
    ANOTHER_VAR: 'another-value'

functions:
  hello:
    handler: src/root/hello.handler
    events:
      - http:
          path: /
          method: get
    package:
      individually: true
      include:
        - src/root/hello.py

  getData:
    handler: src/basic/getData.handler
    events:
      - http:
          path: /basic
          method: get
    package:
      individually: true
      include:
        - src/basic/getData.py

  postData:
    handler: src/basic/postData.handler
    events:
      - http:
          path: /basic
          method: post
    package:
      individually: true
      include:
        - src/basic/postData.py

  getItems:
    handler: src/settings/getItems.handler
    events:
      - http:
          path: /settings
          method: get
    package:
      individually: true
      include:
        - src/settings/getItems.py

  getItemByName:
    handler: src/settings/getItemByName.handler
    events:
      - http:
          path: /settings/{name}
          method: get
    package:
      individually: true
      include:
        - src/settings/getItemByName.py

  putItem:
    handler: src/settings/putItem.handler
    events:
      - http:
          path: /settings
          method: put
    package:
      individually: true
      include:
        - src/settings/putItem.py

  authorizeUser:
    handler: src/user/authorizeUser.handler
    events:
      - http:
          path: /user
          method: post
          authorizer: aws_iam
    package:
      individually: true
      include:
        - src/user/authorizeUser.py

  getEvents:
    handler: src/events/getEvents.handler
    layers:
      - arn:aws:lambda:ap-southeast-1:017820698732:layer:python-layer-google-api:1
    environment:
      GOOGLE_SHEET_URL: ${self:custom.${self:provider.stage}.GOOGLE_SHEET_URL}
    events:
      - http:
          path: /events
          method: get
    package:
      individually: true
      include:
        - src/events/getEvents.py
        - src/events/credentials.${self:provider.stage}.json

custom:
  dev:
    GOOGLE_SHEET_URL: 'https://docs.google.com/spreadsheets/d/158k7h98Ri8VCgG3hRNUPtWeiTOPGG81abnlIP0q8low/edit'

package:
  exclude:
    - .serverless/**
    - docs/**
    - my_layers/**
    - node_modules/**
    - src/**
    - __pycache__/**
    - .gitignore
    - package.json
    - package-lock.json
    - README.md

plugins:
  - serverless-offline
