# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: haiyun
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-python-http-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-python-http-api

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  role: arn:aws:iam::017820698732:role/MyLambdaDynamoDBExecutionRole

  environment:
    MY_ENV_VAR: 'my-value'
    ANOTHER_VAR: 'another-value'

functions:
  hello:
    handler: src/root/hello.handler
    events:
      - http:
          path: /
          method: get

  getData:
    handler: src/basic/getData.handler
    events:
      - http:
          path: /basic
          method: get

  postData:
    handler: src/basic/postData.handler
    events:
      - http:
          path: /basic
          method: post

  getItem:
    handler: src/dynamoDB/getItem.handler
    events:
      - http:
          path: /setting
          method: get

  putItem:
    handler: src/dynamoDB/putItem.handler
    events:
      - http:
          path: /setting
          method: post

package:
  include:
    - src/**
  exclude:
    - node_modules/**
    - __pycache__/**
    - package.json
    - package-lock.json
    - .gitignore
    - README.md

plugins:
  - serverless-offline
