# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: haiyun
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-python-http-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-python-http-api

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  role: arn:aws:iam::017820698732:role/MyLambdaDynamoDBExecutionRole

  environment:
    MY_ENV_VAR: 'my-value'
    ANOTHER_VAR: 'another-value'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
